name: Run API Tests

on:
  push:
      branches: [main]
  workflow_dispatch:
  schedule:
      - cron: '30 2 * * *'
      - cron: '30 13 * * *'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in repository
        run: ls -R .

      # - name: Install nodejs and npm
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      # - name: Install newman & htmlextra
      #   run: | # Multi line commands - we need to use single pipe 
      #     npm install -g newman
      #     npm install -g newman-reporter-htmlextra

      # - name: Run postman collection with newman
      #   run: |               
      #     newman run postman/In-warranty_Flow_Collection_Random_Data.postman_collection.json \
      #       -e QA.postman_environment.json \
      #       -r htmlextra
          
  
