name: Run API Tests

on:
  push:
      branches: [main]
  workflow_dispatch:
  schedule:
      - cron: '30 2 * * *'
      - cron: '30 13 * * *'

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install newman & htmlextra
        run: | # Multi line commands - we need to use single pipe 
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run postman collection with newman
        run: |               
          newman run In-warranty_Flow_Collection_Random_Data.postman_collection.json \
            -e QA.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Newman collection report achieve
        if: always() # ensure that archive executed irrespective whether previous step has passed or not
        uses: actions/upload-artifact@v4.6.2
        with:
         name: Newman Report
         path: newman/*.html

      - name: Creating Github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Github will generate the token by itself
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow Test Execution Report
          to: iyashwanthkrishna000@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: | 
                Hi,
                Phoenix In-warranty Flow Test has been executed. The report has been published and the 
                url is - https://yashwanthk-idexcel.github.io/In-warranty-Flow-Collection/
          attachments: newman/index.html
                
          
      
        
          
  
